#!/bin/bash
rm /etc/ssh/ssh_host_* >/dev/null
dpkg-reconfigure openssh-server >/dev/null 2>&1

for file in /etc/ssh/ssh_host_*; do
    var=$(echo $file | sed "s#/\|\.#_#g");
    echo "--env $var=$(base64 -w 0 $file)";
done
